set serveroutput on;
set verify off;

DECLARE

	LATEST_ORDER NUMBER := 0;
	
	FT INTEGER;
	FF VARCHAR(40);
	FFF NUMBER;
	FFFF VARCHAR(25);
	FFFFF VARCHAR(25);
	FFFFFF INTEGER;
	FFFFFFF NUMBER;
	F9 DATE;
	TOTALF NUMBER := 0;
	
BEGIN

	FOR F IN (SELECT * FROM ORDERS WHERE O_ID IN (SELECT MAX(O_ID) AS MAXIMUM FROM ORDERS)) LOOP
			FT := F.O_ID;
			FF := F.O_ITEMS;
			FFF := F.QUANTITY;
			FFFF := F.CUSTOMER_NAME;
			FFFFF := F.CUSTOMER_ADDRESS;
			FFFFFF := F.L_ID;
			F9 := F.THE_DATE;
			
			--DBMS_OUTPUT.PUT_LINE('TOKEN NO.: ' || FT);
			DBMS_OUTPUT.PUT_LINE('ORDER ITEM :' ||FF);
			DBMS_OUTPUT.PUT_LINE('QUANTITY OF ' ||FF ||':'||FFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME' || FFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFF);
	END LOOP;
	
	DBMS_OUTPUT.PUT_LINE('TOKEN NO.: ' || FT);
	DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME :' || FFFF);
	DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS :' || FFFFF);
	DBMS_OUTPUT.PUT_LINE('DATE :' || F9);
	--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFFF);
	
		
	FOR Z IN (SELECT * FROM ORDERS WHERE O_ID IN (SELECT MAX(O_ID) AS MAXIMUM FROM ORDERS)) LOOP
			FFFFFFF := Z.PRICE;
			TOTALF := TOTALF + FFFFFFF;
	END LOOP;
	
	DBMS_OUTPUT.PUT_LINE('TOTAL PRICE :' || TOTALF);

END;
/