


ACCEPT X PROMPT 'FOR FIRING STAFF PRESS 1 THEN GIVE THE STAFF ID AND IGNORE OTHER COMMAND'

DECLARE

	A INTEGER;
	
	
	FIRESTAFF NUMBER := 0;
	FIRESTAFF_ID INTEGER;
	
	CHECKING_ORDER NUMBER := 0;
	CHECKING_ORDER_ID INTEGER;
	
	F1 INTEGER := 0;
	FF VARCHAR(40);
	FFF NUMBER;
	FFFF VARCHAR(25);
	FFFFF VARCHAR(25);
	FFFFFF INTEGER;
	FFFFFFF NUMBER;
	TOTALF NUMBER := 0;
	AREA VARCHAR(25);
	
	TOTAL_ORDERS NUMBER := 0;
	N1 NUMBER := 0;
	
	LATEST_ORDER NUMBER := 0;
	
	F2 VARCHAR(40);
	F3 NUMBER;
	F4 VARCHAR(25);
	F5 VARCHAR(25);
	F6 INTEGER;
	F7 NUMBER;
	TOTALF7 NUMBER := 0;
	
	TOTAL_SELL NUMBER := 0;
	N111 NUMBER := 0;
	N11 NUMBER := 0;
	N NUMBER := 0;
	

BEGIN

	A := &X;
	
	IF(A=1) THEN
		FIRESTAFF_ID := &X;
	
  
		DELETE FROM STAFFS WHERE S_ID = FIRESTAFF_ID;
		
	
	ELSIF(A=3) THEN
		FOR Z IN (SELECT COUNT(O_ID) AS COUNTT FROM ORDERS) LOOP
			N1 := Z.COUNTT;
		END LOOP;
	
		DBMS_OUTPUT.PUT_LINE('TOTAL ORDERS :' ||N1);
	
	ELSIF(A=4) THEN
		FOR F IN (SELECT * FROM ORDERS WHERE O_ID IN (SELECT MAX(O_ID) AS MAXIMUM FROM ORDERS)) LOOP
			F2 := F.O_ITEMS;
			F3 := F.QUANTITY;
			F4 := F.CUSTOMER_NAME;
			F5 := F.CUSTOMER_ADDRESS;
			F6 := F.L_ID;
			
			DBMS_OUTPUT.PUT_LINE('ORDER ITEM :' ||F2);
			DBMS_OUTPUT.PUT_LINE('QUANTITY OF' ||F2 ||':'||F3);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME' || FFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFF);
		END LOOP;
	
	
		DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME :' || F4);
		DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS :' || F5);
		--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFFF);
	
		
		FOR Z IN (SELECT * FROM ORDERS WHERE O_ID IN (SELECT MAX(O_ID) AS MAXIMUM FROM ORDERS)) LOOP
			F7 := Z.PRICE;
			TOTALF7 := TOTALF7 + F7;
		END LOOP;
	
		DBMS_OUTPUT.PUT_LINE('TOTAL PRICE :' || TOTALF7);
		
	ELSIF(A=5) THEN
		FOR Z IN (SELECT * FROM ORDERS) LOOP
			N1 := Z.PRICE;
			N := N + N1;
		END LOOP;
	
		DBMS_OUTPUT.PUT_LINE('TOTAL SELL :' ||N);
	
	ELSE DBMS_OUTPUT.PUT_LINE('INVALID INPUT');
	
	END IF;
		
END;
/