
SELECT * FROM MENU;

CREATE OR REPLACE VIEW RECEIPT (TOKEN_NUM, ORDERED_ITEMS, UNITS, PRICES, NAME, ADDRESS) AS SELECT O.O_ID, O.O_ITEMS, O.QUANTITY, O.PRICE, O.CUSTOMER_NAME, O.CUSTOMER_ADDRESS FROM ORDERS O;

DECLARE
	
	F1 INTEGER;
	FF VARCHAR(40);
	FFF NUMBER;
	FFFF VARCHAR(25);
	FFFFF VARCHAR(25);
	FFFFFF INTEGER;
	FFFFFFF NUMBER;
	TOTALF NUMBER := 0;
	
	

BEGIN

	FOR F IN (SELECT * FROM ORDERS WHERE O_ID IN (SELECT MAX(O_ID) AS MAXIMUM FROM ORDERS)) LOOP
			F1 := F.O_ID;
			FF := F.O_ITEMS;
			FFF := F.QUANTITY;
			FFFF := F.CUSTOMER_NAME;
			FFFFF := F.CUSTOMER_ADDRESS;
			FFFFFF := F.L_ID;
			
			--DBMS_OUTPUT.PUT_LINE('ORDER ITEM :' ||FF);
			--DBMS_OUTPUT.PUT_LINE('QUANTITY OF' ||FF ||':'||FFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME' || FFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFF);
			--DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS' || FFFF);
	END LOOP;
	
	
	DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME :' || FFFF);
	DBMS_OUTPUT.PUT_LINE('CUSTOMER ADDRESS :' || FFFFF);
	DBMS_OUTPUT.pUT_LINE('TOKEN NO :' || F1);

END;
/



	
	--SELECT * FROM RECEIPT WHERE TOKEN_NUM IN (SELECT MAX(TOKEN_NUM) AS MAXIMUM FROM RECEIPT);
	SELECT ORDERED_ITEMS, UNITS, PRICES FROM RECEIPT WHERE TOKEN_NUM IN (SELECT MAX(TOKEN_NUM) AS MAXIMUM FROM RECEIPT);	
	
DECLARE

	ZZ NUMBER := 0;
	PRICEE NUMBER := 0;
	
BEGIN
	
	FOR Z IN (SELECT * FROM ORDERS WHERE O_ID IN (SELECT MAX(O_ID) AS MAXIMUM FROM ORDERS)) LOOP
		ZZ := Z.PRICE;
		PRICEE := PRICEE + ZZ;
	END LOOP;
	
	DBMS_OUTPUT.PUT_LINE('TOTAL PRICE : '||PRICEE);

END;
/
	

